version: "3"
services:
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
  proxy:
    image: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "443"
    labels:
      - traefik.frontend.entryPoints=https
      - traefik.protocol=https
    command: "npm start"
